'use client';

import { useState, useEffect, useRef } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useUser } from '@clerk/nextjs';
import { messageApi, matchApi, userApi, getImageUrl } from '@/lib/api';
import { socketService } from '@/lib/socket';
import { FaPaperPlane, FaArrowLeft, FaCircle, FaRobot } from 'react-icons/fa';
import { IoMdMale, IoMdFemale } from 'react-icons/io';
import { HiLocationMarker } from 'react-icons/hi';
import toast from 'react-hot-toast';
import PremiumMessageModal from '@/components/ui/PremiumMessageModal';

interface Message {
  _id: string;
  senderId: string;
  receiverId: string;
  content: string;
  createdAt: string;
  read: boolean;
  isNew?: boolean; // For animation
  isAIGenerated?: boolean; // If message was generated by AI
}

interface OtherUser {
  _id: string;
  username: string;
  profilePhoto?: string;
  age: number;
  gender: 'male' | 'female' | 'other';
  location?: {
    city?: string;
    country?: string;
  };
  lastSeen: string;
  isAI?: boolean; // If this is an AI profile
}

const COUNTDOWN_DURATION = 10 * 60; // 10 minutes in seconds
const COUNTDOWN_STORAGE_KEY = 'thaitide_global_message_countdown'; // Global countdown across all chats
const HAS_SENT_MESSAGE_KEY = 'thaitide_has_sent_first_message'; // Track if user has ever sent a message
const DRAFT_STORAGE_KEY_PREFIX = 'thaitide_message_draft_'; // Prefix for draft messages per chat

export default function MessagesPage() {
  const params = useParams();
  const router = useRouter();
  const { user: clerkUser, isLoaded } = useUser();
  const matchId = params.matchId as string;
  const [messages, setMessages] = useState<Message[]>([]);
  const [newMessage, setNewMessage] = useState('');
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [typing, setTyping] = useState(false);
  const [sending, setSending] = useState(false);
  const [otherUser, setOtherUser] = useState<OtherUser | null>(null);
  const [currentUserId, setCurrentUserId] = useState<string>('');
  const [userMessageCount, setUserMessageCount] = useState(0);
  const [showPremiumModal, setShowPremiumModal] = useState(false);
  const [isPremiumUser, setIsPremiumUser] = useState(false);
  const [countdown, setCountdown] = useState(COUNTDOWN_DURATION);
  const [pendingMessage, setPendingMessage] = useState('');
  const [hasSentFirstMessage, setHasSentFirstMessage] = useState(false);
  const [shouldStartCountdown, setShouldStartCountdown] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // Initialize global countdown timer from localStorage
  useEffect(() => {
    // Check if user has sent their first message ever
    const hasSent = localStorage.getItem(HAS_SENT_MESSAGE_KEY) === 'true';
    setHasSentFirstMessage(hasSent);
    
    // Load global countdown
    const savedEndTime = localStorage.getItem(COUNTDOWN_STORAGE_KEY);
    
    if (savedEndTime) {
      const endTime = parseInt(savedEndTime, 10);
      const now = Date.now();
      const remainingSeconds = Math.max(0, Math.floor((endTime - now) / 1000));
      setCountdown(remainingSeconds);
    } else if (!hasSent) {
      // No countdown running and user hasn't sent first message yet - no countdown needed
      setCountdown(0);
    }
  }, []);

  // Countdown timer tick
  useEffect(() => {
    if (countdown <= 0 || isPremiumUser) return;

    const timer = setInterval(() => {
      setCountdown((prev) => {
        if (prev <= 1) {
          clearInterval(timer);
          return 0;
        }
        return prev - 1;
      });
    }, 1000);

    return () => clearInterval(timer);
  }, [countdown, isPremiumUser]);

  // Start global countdown
  const startGlobalCountdown = () => {
    const endTime = Date.now() + COUNTDOWN_DURATION * 1000;
    localStorage.setItem(COUNTDOWN_STORAGE_KEY, endTime.toString());
    localStorage.setItem(HAS_SENT_MESSAGE_KEY, 'true');
    setHasSentFirstMessage(true);
    setCountdown(COUNTDOWN_DURATION);
  };

  // Reset countdown after user sends a message when timer reached 0
  const resetCountdownAfterSend = () => {
    startGlobalCountdown();
  };

  useEffect(() => {
    async function init() {
      if (!isLoaded || !clerkUser) return;
      
      try {
        // Get the database user ID from Clerk ID
        const profileResponse = await userApi.getProfileByClerkId(clerkUser.id);
        const dbUserId = profileResponse.data.user._id;
        const userProfile = profileResponse.data.user;
        setCurrentUserId(dbUserId);
        
        // Check if user has premium (either via subscription or direct isPremium flag)
        if (userProfile.isPremium || userProfile.subscription?.status === 'active') {
          setIsPremiumUser(true);
        }
        
        // Store in localStorage for consistency
        localStorage.setItem('userId', dbUserId);
        
        // Get match details to find the other user
        try {
          const response = await matchApi.getMatchDetails(matchId, dbUserId);
          setOtherUser(response.data.otherUser);
        } catch (error: any) {
          // If match details fail, show error and allow user to go back
          console.error('Match details failed:', error);
          setLoadError('Conversation not found. Please try again.');
          setLoading(false);
          return;
        }
      } catch (error) {
        console.error('Failed to load match details:', error);
        setLoadError('Failed to load chat. Please try again.');
        setLoading(false);
      }
    }
    
    init();
  }, [matchId, clerkUser, isLoaded]);

  useEffect(() => {
    if (!currentUserId) return;
    
    loadMessages();
    
    // Connect to socket
    const socket = socketService.connect(currentUserId);

    // Listen for new messages
    const handleNewMessage = (data: any) => {
      if (data.matchId?.toString() === matchId) {
        setMessages((prev) => [...prev, { ...data.message, isNew: true }]);
        
        // Mark the incoming message as read since user is viewing the conversation
        if (data.message.receiverId?.toString() === currentUserId) {
          socketService.emitMarkAsRead({ matchId, userId: currentUserId });
        }
      }
    };

    const handleTyping = (data: any) => {
      if (data.matchId?.toString() === matchId && data.userId !== currentUserId) {
        setTyping(true);
        setTimeout(() => setTyping(false), 3000);
      }
    };

    const handleMessageSent = (data: any) => {
      if (data.message && (data.matchId?.toString() === matchId || data.message.matchId?.toString() === matchId)) {
        // Replace optimistic message with real message from server
        setMessages((prev) =>
          prev.map((msg) =>
            msg._id.toString().startsWith('temp-')
              ? { ...data.message, isNew: false }
              : msg
          )
        );
        
        // Start countdown only after server confirms message was saved
        setShouldStartCountdown((prev) => {
          if (prev) {
            startGlobalCountdown();
          }
          return false;
        });
      }
    };

    const handleMessageError = (data: any) => {
      // Remove any optimistic messages that failed to send
      setMessages((prev) => prev.filter((msg) => !msg._id.toString().startsWith('temp-')));
      setUserMessageCount((prev) => Math.max(0, prev - 1));
      setShouldStartCountdown(false);
      toast.error(data.error || 'Failed to send message');
    };

    socketService.onNewMessage(handleNewMessage);
    socketService.onTyping(handleTyping);
    socketService.onMessageSent(handleMessageSent);
    socketService.onMessageError(handleMessageError);

    return () => {
      socketService.removeListener('new_message', handleNewMessage);
      socketService.removeListener('user_typing', handleTyping);
      socketService.removeListener('message_sent', handleMessageSent);
      socketService.removeListener('message_error', handleMessageError);
    };
  }, [matchId, currentUserId]);

  useEffect(() => {
    scrollToBottom();
  }, [messages]);

  // Load draft message from localStorage on mount
  useEffect(() => {
    if (!matchId) return;
    const savedDraft = localStorage.getItem(`${DRAFT_STORAGE_KEY_PREFIX}${matchId}`);
    if (savedDraft) {
      setNewMessage(savedDraft);
    }
  }, [matchId]);

  // Save draft message to localStorage when input changes (debounced)
  useEffect(() => {
    if (!matchId) return;
    
    const timeoutId = setTimeout(() => {
      if (newMessage.trim()) {
        localStorage.setItem(`${DRAFT_STORAGE_KEY_PREFIX}${matchId}`, newMessage);
      } else {
        localStorage.removeItem(`${DRAFT_STORAGE_KEY_PREFIX}${matchId}`);
      }
    }, 300); // Debounce 300ms

    return () => clearTimeout(timeoutId);
  }, [newMessage, matchId]);

  const loadMessages = async () => {
    try {
      setLoading(true);
      const response = await messageApi.getMessages(matchId);
      const loadedMessages = response.data.messages;
      setMessages(loadedMessages);
      
      // Count messages sent by current user in this conversation
      if (currentUserId) {
        const sentByCurrentUser = loadedMessages.filter(
          (msg: Message) => msg.senderId === currentUserId || 
            (typeof msg.senderId === 'object' && (msg.senderId as any)?._id === currentUserId)
        ).length;
        setUserMessageCount(sentByCurrentUser);
      }
      
      // Mark all messages in this conversation as read via socket for real-time badge update
      if (currentUserId) {
        socketService.emitMarkAsRead({ matchId, userId: currentUserId });
      }
    } catch (error) {
      toast.error('Failed to load messages');
    } finally {
      setLoading(false);
    }
  };

  const sendMessage = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newMessage.trim() || sending) return;

    // Ensure we have the other user's ID before sending
    if (!otherUser?._id) {
      toast.error('Unable to send message. Please refresh the page.');
      return;
    }

    // For non-premium users: check global countdown
    // If user has already sent a message before (hasSentFirstMessage) and countdown is running, show modal
    if (!isPremiumUser && hasSentFirstMessage && countdown > 0) {
      setPendingMessage(newMessage.trim());
      setShowPremiumModal(true);
      return;
    }

    await doSendMessage(newMessage.trim());
  };

  // Handle sending from modal when countdown reaches 0
  const handleSendFromModal = async () => {
    if (pendingMessage) {
      await doSendMessage(pendingMessage);
      setPendingMessage('');
      setShowPremiumModal(false);
    } else if (newMessage.trim()) {
      await doSendMessage(newMessage.trim());
      setShowPremiumModal(false);
    }
  };

  const doSendMessage = async (messageContent: string) => {
    if (!messageContent || sending) return;

    // Ensure we have a valid receiver ID
    if (!otherUser?._id) {
      toast.error('Unable to send message. Please refresh the page.');
      return;
    }

    const receiverId = otherUser._id;
    
    // Clear input and draft immediately for better UX
    setNewMessage('');
    localStorage.removeItem(`${DRAFT_STORAGE_KEY_PREFIX}${matchId}`);
    setSending(true);

    // Check if this is the very first message ever (globally) or after countdown finished
    const isVeryFirstMessage = !hasSentFirstMessage;
    const isAfterCountdown = hasSentFirstMessage && countdown === 0;

    // Optimistic update - add message immediately with animation
    const optimisticMessage: Message = {
      _id: `temp-${Date.now()}`,
      senderId: currentUserId,
      receiverId,
      content: messageContent,
      createdAt: new Date().toISOString(),
      read: false,
      isNew: true
    };
    
    setMessages(prev => [...prev, optimisticMessage]);
    setUserMessageCount(prev => prev + 1);

    try {
      // Mark that countdown should start when message is confirmed
      if (!isPremiumUser && (isVeryFirstMessage || isAfterCountdown)) {
        setShouldStartCountdown(true);
      }
      
      socketService.sendMessage({
        matchId,
        senderId: currentUserId,
        receiverId,
        content: messageContent
      });
      
      // The message_sent event handler will replace the temp message and start countdown
    } catch (error) {
      toast.error('Failed to send message');
      // Remove optimistic message on error and revert counter
      setMessages(prev => prev.filter(msg => msg._id !== optimisticMessage._id));
      setUserMessageCount(prev => prev - 1);
      setShouldStartCountdown(false);
    } finally {
      setSending(false);
      inputRef.current?.focus();
    }
  };

  const handleTypingEvent = () => {
    if (!otherUser?._id) return;
    socketService.emitTyping({
      matchId,
      userId: currentUserId,
      receiverId: otherUser._id
    });
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const formatLastSeen = (lastSeen: string) => {
    const date = new Date(lastSeen);
    const now = new Date();
    const diffMs = now.getTime() - date.getTime();
    const diffMins = Math.floor(diffMs / 60000);
    const diffHours = Math.floor(diffMs / 3600000);
    const diffDays = Math.floor(diffMs / 86400000);

    if (diffMins < 5) return 'Online now';
    if (diffMins < 60) return `${diffMins} min ago`;
    if (diffHours < 24) return `${diffHours}h ago`;
    if (diffDays < 7) return `${diffDays}d ago`;
    return date.toLocaleDateString();
  };

  const getGenderIcon = (gender: string) => {
    if (gender === 'male') return <IoMdMale className="text-blue-500" />;
    if (gender === 'female') return <IoMdFemale className="text-pink-500" />;
    return null;
  };

  if (loadError) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-pink-50 via-white to-purple-50">
        <div className="text-center">
          <div className="text-6xl mb-4">😕</div>
          <h3 className="text-xl font-semibold text-gray-800 mb-2">{loadError}</h3>
          <button
            onClick={() => router.push('/messages')}
            className="bg-gradient-to-r from-pink-500 to-purple-600 text-white px-6 py-3 rounded-lg font-semibold hover:opacity-90 transition-opacity"
          >
            Back to Messages
          </button>
        </div>
      </div>
    );
  }

  if (!isLoaded || loading || !otherUser) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-gradient-to-br from-pink-50 via-white to-purple-50">
        <div className="text-center">
          <div className="animate-spin rounded-full h-16 w-16 border-b-4 border-pink-500 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading messages...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-screen md:h-[calc(100vh-64px)] overflow-hidden bg-gradient-to-br from-pink-50 via-white to-purple-50 md:mt-16">
      <div className="max-w-4xl mx-auto h-full flex flex-col overflow-hidden">
        {/* Enhanced Header */}
        <div className="flex-shrink-0 bg-white shadow-md px-4 py-3 flex items-center gap-4 border-b border-gray-100">
          <button
            onClick={() => router.back()}
            className="p-2 hover:bg-gray-100 rounded-full transition-colors"
          >
            <FaArrowLeft className="text-gray-600 text-lg" />
          </button>
          
          {otherUser && (
            <div 
              className="flex items-center gap-3 flex-1 cursor-pointer hover:bg-gray-50 rounded-lg p-2 -m-2 transition-colors"
              onClick={() => router.push(`/profile/${otherUser._id}`)}
            >
              {/* Profile Photo */}
              <div className="relative">
                <div className="w-12 h-12 rounded-full overflow-hidden bg-gradient-to-r from-pink-400 to-purple-500 p-0.5">
                  <div className="w-full h-full rounded-full overflow-hidden bg-white">
                    {otherUser.profilePhoto ? (
                      <img
                        src={getImageUrl(otherUser.profilePhoto)}
                        alt={otherUser.username}
                        className="w-full h-full object-cover"
                      />
                    ) : (
                      <div className="w-full h-full bg-gradient-to-r from-pink-400 to-purple-500 flex items-center justify-center text-white text-lg font-semibold">
                        {otherUser.username.charAt(0).toUpperCase()}
                      </div>
                    )}
                  </div>
                </div>
                {/* Online indicator */}
                {formatLastSeen(otherUser.lastSeen) === 'Online now' && (
                  <div className="absolute bottom-0 right-0 w-3.5 h-3.5 bg-green-500 rounded-full border-2 border-white"></div>
                )}
              </div>
              
              {/* User Info */}
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2">
                  <h2 className="text-lg font-semibold text-gray-800 truncate">
                    @{otherUser.username}
                  </h2>
                  <span className="text-gray-500">{otherUser.age}</span>
                  {getGenderIcon(otherUser.gender)}
                  {otherUser.isAI && (
                    <span className="flex items-center gap-1 px-2 py-0.5 bg-gradient-to-r from-cyan-500 to-blue-500 text-white text-xs rounded-full font-medium">
                      <FaRobot className="text-[10px]" />
                      AI
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-3 text-sm text-gray-500">
                  {otherUser.location?.city && (
                    <span className="flex items-center gap-1 truncate">
                      <HiLocationMarker className="text-pink-500 flex-shrink-0" />
                      <span className="truncate">
                        {otherUser.location.city}
                        {otherUser.location.country && `, ${otherUser.location.country}`}
                      </span>
                    </span>
                  )}
                  <span className="flex items-center gap-1 flex-shrink-0">
                    <FaCircle 
                      className={`text-[8px] ${
                        formatLastSeen(otherUser.lastSeen) === 'Online now' 
                          ? 'text-green-500' 
                          : 'text-gray-400'
                      }`} 
                    />
                    {formatLastSeen(otherUser.lastSeen)}
                  </span>
                </div>
              </div>
            </div>
          )}
        </div>

        {/* Messages */}
        <div className="flex-1 overflow-y-auto min-h-0 p-4 space-y-3">
          {messages.length === 0 && !loading && (
            <div className="text-center text-gray-500 mt-10">
              <p className="text-lg">Say hello to @{otherUser?.username || 'your match'}! 👋</p>
              <p className="text-sm mt-2">Start a conversation</p>
            </div>
          )}
          
          {messages.map((message, index) => {
            const isOwn = message.senderId === currentUserId || 
                          (typeof message.senderId === 'object' && (message.senderId as any)?._id === currentUserId);
            const showTimestamp = index === 0 || 
              new Date(message.createdAt).getTime() - new Date(messages[index - 1].createdAt).getTime() > 300000;
            
            return (
              <div key={message._id}>
                {showTimestamp && (
                  <div className="text-center text-xs text-gray-400 my-4">
                    {new Date(message.createdAt).toLocaleDateString([], { 
                      weekday: 'short', 
                      month: 'short', 
                      day: 'numeric',
                      hour: '2-digit',
                      minute: '2-digit'
                    })}
                  </div>
                )}
                <div
                  className={`flex ${isOwn ? 'justify-end' : 'justify-start'} ${
                    message.isNew ? 'animate-message-in' : ''
                  }`}
                >
                  <div
                    className={`max-w-[75%] md:max-w-md px-4 py-2.5 rounded-2xl transform transition-all duration-300 ${
                      isOwn
                        ? 'bg-gradient-to-r from-pink-500 to-purple-600 text-white rounded-br-md'
                        : 'bg-white text-gray-800 shadow-md rounded-bl-md'
                    } ${message.isNew ? 'scale-100' : ''}`}
                  >
                    <p className="whitespace-pre-wrap break-words">{message.content}</p>
                    <div className={`flex items-center gap-2 mt-1 ${isOwn ? 'justify-end' : ''}`}>
                      {!isOwn && message.isAIGenerated && (
                        <span className="flex items-center gap-0.5 text-[10px] text-cyan-500 font-medium">
                          <FaRobot className="text-[8px]" />
                          AI
                        </span>
                      )}
                      <p className={`text-xs ${isOwn ? 'text-pink-100' : 'text-gray-400'}`}>
                        {new Date(message.createdAt).toLocaleTimeString([], { 
                          hour: '2-digit', 
                          minute: '2-digit' 
                        })}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            );
          })}
          
          {typing && (
            <div className="flex justify-start animate-fade-in">
              <div className="bg-white px-4 py-3 rounded-2xl shadow-md rounded-bl-md">
                <div className="flex space-x-1.5">
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.15s' }}></div>
                  <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.3s' }}></div>
                </div>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Input */}
        <div className="flex-shrink-0 bg-white border-t border-gray-200 p-4 pb-safe">
          <form onSubmit={sendMessage} className="flex gap-3 items-end">
            <input
              ref={inputRef}
              type="text"
              value={newMessage}
              onChange={(e) => setNewMessage(e.target.value)}
              onKeyPress={handleTypingEvent}
              placeholder="Type a message..."
              className="flex-1 px-4 py-3 border border-gray-200 rounded-full focus:ring-2 focus:ring-pink-500 focus:border-transparent transition-all bg-gray-50 focus:bg-white"
            />
            <button
              type="submit"
              disabled={!newMessage.trim() || sending}
              className={`w-12 h-12 rounded-full flex items-center justify-center transition-all duration-300 transform ${
                newMessage.trim() && !sending
                  ? 'bg-gradient-to-r from-pink-500 to-purple-600 hover:shadow-lg hover:scale-105 active:scale-95'
                  : 'bg-gray-300 cursor-not-allowed'
              }`}
            >
              <FaPaperPlane 
                className={`text-white transition-transform duration-300 ${
                  sending ? 'translate-x-1 -translate-y-1' : ''
                }`} 
              />
            </button>
          </form>
        </div>
      </div>

      {/* CSS for animations */}
      <style jsx global>{`
        @keyframes messageIn {
          0% {
            opacity: 0;
            transform: translateY(20px) scale(0.95);
          }
          100% {
            opacity: 1;
            transform: translateY(0) scale(1);
          }
        }
        
        @keyframes fadeIn {
          from {
            opacity: 0;
          }
          to {
            opacity: 1;
          }
        }
        
        .animate-message-in {
          animation: messageIn 0.3s ease-out forwards;
        }
        
        .animate-fade-in {
          animation: fadeIn 0.2s ease-out forwards;
        }
        
        .pb-safe {
          padding-bottom: max(1rem, env(safe-area-inset-bottom));
        }
      `}</style>

      {/* Premium Message Modal */}
      {otherUser && (
        <PremiumMessageModal
          isOpen={showPremiumModal}
          onClose={() => {
            setShowPremiumModal(false);
            setPendingMessage('');
          }}
          otherUser={otherUser}
          subscriptionPrice="$9.99"
          countdown={countdown}
          canSendMessage={countdown === 0}
          onSendNow={handleSendFromModal}
        />
      )}
    </div>
  );
}
